#!/usr/bin/env ruby

if ARGV.size == 1  # assume it's the "base" branch
  base = ARGV.first
else
  base = "staging"
end

url = "https://github.com/subpoprecords/mycelium/pull/new/" +
      "subpoprecords:#{base}...subpoprecords:" +
      `git branch | grep ^\*`.split.last.chomp

`echo #{url} | pbcopy`
