development:
  adapter: sqlite #postgresql
  encoding: unicode
  database: lpfm_development
  pool: 5
  password:
  socket: /var/pgsql_socket

test:
  adapter: postgresql
  encoding: unicode
  database: lpfm_test
  pool: 5
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: lpfm_development
#   pool: 5
#   username: lpfm_website
#   password:
#   socket: /var/pgsql_socket
